FROM php:8.1.8-fpm

ARG DOCKER_PHP_DATE_TIMEZONE

ENV DOCKER_PHP_DATE_TIMEZONE=$DOCKER_PHP_DATE_TIMEZONE

COPY ./docker/php-fpm/ini/php-dev.ini /usr/local/etc/php/php.ini

RUN apt update && apt install -y vim

CMD php-fpm
